### ISSUE TITLE
Raiden's To-do List

### ISSUE THREAD

**Issue by ThunderDraconius** [PMDShift/Home#5]
- [x] Map: Moonlight Cavern, Sunlight Lake's entrance maps
- [x] Item: Update to Gen 8's Items
- [x] Item: Create variations for Dust, Apple, Gem, Globe
- [x] Sprite: Shiny Shuckle
- [x] Feature: Shift Coupon's distribution
- [x] Map: Petal Garden
- [ ] Map: Aqua Road

**Comment by ThunderDraconius** [comment]
- [ ] Map: Moonlight Cavern's entrance map
- [ ] Item: Create variations for Dusts, Apple
